name: dbt CI

on:
  pull_request:
    branches:
      - master

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    environment: DBT_BTC
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}  # PR vs push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.4 dbt-snowflake==1.9.4


      - name: Set up dbt profile and private key
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILES_YML" > ~/.dbt/profiles.yml
          echo "$DBT_PRIVATE_KEY" > ~/.dbt/rsa_key
          chmod 600 ~/.dbt/rsa_key
        env:
          DBT_PROFILES_YML: ${{ secrets.DBT_PROFILES_YML }}
          DBT_PRIVATE_KEY: ${{ secrets.DBT_PRIVATE_KEY }}



      - name: Install dbt deps
        run: dbt deps

      - name: dbt debug
        run: dbt debug --target "${{ env.DBT_TARGET }}"

      - name: dbt run
        run: dbt run --target "${{ env.DBT_TARGET }}"
