version: 2


models:
  - name: stg_btc 
    columns:
      - name: HASH_KEY
        tests:
          - unique
          - not_null

  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')
  


exposures:

  - name: btc_whale_alert_exposure
    label: BTC Whale alert
    type: dashboard
    maturity: high
    url: https://lookerstudio.google.com/reporting/1e6cd860-9716-4179-8cd1-2be00c1db0c0
    description: >
      BTC Whale alert transactions report"?

    depends_on:
      - ref('whale_alert')

    owner:
      name: Daniel Weigel




